name: Offerings
main: com.keithlawless.plugins.offerings.OfferingsPlugin
version: 1.0
api-version: 1.15
commands:
  offerings-set-altar:
    description: Set the Altar where players will make their Offerings
    usage: /<command>
  offerings-set-cancel:
    description: Cancel the Set Altar command, no matter who has the magic wand. Useful to take control from another op.
    usage: /<command>
